name: Flow_Tests

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    
    - name: Set up iperf3
      run: |
        sudo apt-get update
        sudo apt-get install iperf3

    - name: Set up pyATS    
      run: |
        pip install pyats[full]
    
    - name: PyTS run
      run: |
        pyats run job py_job.py
    
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: outpu.json
  